### ISSUE TITLE
npm audit: 5 moderate severity vulnerabilites

### ISSUE THREAD

**Issue by MaxterBattle** [rossmoody/ts-extension-starter#4]
It looks like these are in dependencies of *rollup-plugin-chrome-extension*, and that upgrading it to v 4.0.1-9 or greater will fix.  It looks like v4 is still beta.   Do you want to avoid that?

**Comment by rossmoody** [comment]
Good question. I suppose it makes sense to ensure nothing breaks with the starter, but otherwise, I'm always an advocate for staying current. Good spot on this.
